# 这些是资助该项目的不同方式

# GitHub Sponsors
github: [your-username]

# Patreon
# patreon: your-username

# Open Collective
# open_collective: your-project-name

# Ko-fi
# ko_fi: your-username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: your-project-name

# LiberaPay
# liberapay: your-username

# Issuehunt
# issuehunt: your-username

# Otechie
# otechie: your-username

# Custom (替换为你的赞助链接)
# custom: ["https://buymeacoffee.com/your-username", "https://paypal.me/your-username"]

# 这些是赞助的元数据
# 如果项目是非营利的,可以添加下面的元数据
# nonprofit: true
